---
name: "get price for application"
description: "should return a price response for a given application"
request:
  method: POST
  urlPath: /prices/v1/api/price
  body:
    productId: 35455
    brandId: 1
    applicationDate: "2020-06-14T00:00:00"
  headers:
    Content-Type: application/json
response:
  status: 200
  headers:
    Content-Type: application/json
  body:
    id: 1
    brandId: 1
    priceList: 1
    startDate: "2020-06-14T00:00:00"
    endDate: "2020-12-31T23:59:59"
    price: 35.50
    currency: EUR
